import mongoose from "mongoose";

export const verifyMongoId = (id) => {
    if (mongoose.Types.ObjectId.isValid(id)) {
        // Valid format, but it could still be a 12-byte string generated by chance
        if (new mongoose.Types.ObjectId(id).toString() === id) {
            return true; // Strictly a valid ObjectId
        }
    }
    return false; // Invalid
};